# Project information
site_name: EvO AutoML
site_description: An evolution based framework that adapts to to evolving datastreams based on river
site_author: Cedric Kulbach
site_url: https://github.com/kulbachcedric/EvOAutoML

# Repository
repo_name: EvO AutoML
repo_url: https://github.com/kulbachcedric/EvOAutoML
edit_uri: "https://github.com/kulbachcedric/EvOAutoML"

# Copyright
copyright: Copyright &copy; 2019 - 2020

# Configuration
theme:
    name: material
    language: en
    palette:
        primary: light blue
        accent: grey
    font:
        text: Roboto
        code: Roboto Mono
    #logo: material/cloud
    favicon: material/cloud
    features:
        - navigation.instant
        - navigation.tracking

# Extras
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/kulbachcedric/EvOAutoML

# Google Analytics
google_analytics:
  - UA-63302552-3
  - auto

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
        permalink: true
        toc_depth: "1-3"
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings

extra_javascript:

extra_css:

nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
        - EvO AutoML: evo_automl.md
        - Pipeline Helper: pipelinehelper.md